@extends('backend.layouts.app')

@section('title', 'Reports Dashboard')

@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Reports Dashboard</h3>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-lg-3 col-6">
                            <div class="small-box bg-info">
                                <div class="inner">
                                    <h3>{{ $totalMovies }}</h3>
                                    <p>Total Movies</p>
                                </div>
                                <div class="icon">
                                    <i class="fas fa-film"></i>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3 col-6">
                            <div class="small-box bg-success">
                                <div class="inner">
                                    <h3>{{ $totalUsers }}</h3>
                                    <p>Total Users</p>
                                </div>
                                <div class="icon">
                                    <i class="fas fa-users"></i>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3 col-6">
                            <div class="small-box bg-warning">
                                <div class="inner">
                                    <h3>{{ $totalOrders }}</h3>
                                    <p>Total Orders</p>
                                </div>
                                <div class="icon">
                                    <i class="fas fa-shopping-cart"></i>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3 col-6">
                            <div class="small-box bg-danger">
                                <div class="inner">
                                    <h3>${{ number_format($totalRevenue, 2) }}</h3>
                                    <p>Total Revenue</p>
                                </div>
                                <div class="icon">
                                    <i class="fas fa-dollar-sign"></i>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row mt-4">
                        <div class="col-md-6">
                            <div class="card">
                                <div class="card-header">
                                    <h3 class="card-title">
                                        <i class="fas fa-chart-bar mr-1"></i>
                                        Available Reports
                                    </h3>
                                </div>
                                <div class="card-body">
                                    <div class="list-group">
                                        <a href="{{ route('reports.movie-revenue') }}" class="list-group-item list-group-item-action">
                                            <div class="d-flex w-100 justify-content-between">
                                                <h5 class="mb-1">Movie Revenue Report</h5>
                                                <small><i class="fas fa-arrow-right"></i></small>
                                            </div>
                                            <p class="mb-1">View revenue generated by movies, including purchase counts and total revenue.</p>
                                        </a>
                                        <a href="{{ route('reports.subscription-analytics') }}" class="list-group-item list-group-item-action">
                                            <div class="d-flex w-100 justify-content-between">
                                                <h5 class="mb-1">Subscription Analytics Report</h5>
                                                <small><i class="fas fa-arrow-right"></i></small>
                                            </div>
                                            <p class="mb-1">View subscription plan performance, active subscribers, and revenue.</p>
                                        </a>
                                        <a href="{{ route('reports.user-activity') }}" class="list-group-item list-group-item-action">
                                            <div class="d-flex w-100 justify-content-between">
                                                <h5 class="mb-1">User Activity Report</h5>
                                                <small><i class="fas fa-arrow-right"></i></small>
                                            </div>
                                            <p class="mb-1">View user engagement metrics like watchlist additions, favorites, and purchases.</p>
                                        </a>
                                        <a href="{{ route('reports.content-performance') }}" class="list-group-item list-group-item-action">
                                            <div class="d-flex w-100 justify-content-between">
                                                <h5 class="mb-1">Content Performance Report</h5>
                                                <small><i class="fas fa-arrow-right"></i></small>
                                            </div>
                                            <p class="mb-1">View movie ratings, views, and popularity metrics.</p>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="card">
                                <div class="card-header">
                                    <h3 class="card-title">
                                        <i class="fas fa-shopping-cart mr-1"></i>
                                        Recent Orders
                                    </h3>
                                </div>
                                <div class="card-body p-0">
                                    <table class="table table-striped">
                                        <thead>
                                            <tr>
                                                <th>Order ID</th>
                                                <th>User</th>
                                                <th>Amount</th>
                                                <th>Date</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach($recentOrders as $order)
                                            <tr>
                                                <td><a href="{{ route('order.show', $order->id) }}">#{{ $order->id }}</a></td>
                                                <td>{{ $order->user->name }}</td>
                                                <td>${{ number_format($order->total_amount, 2) }}</td>
                                                <td>{{ $order->created_at->format('M d, Y') }}</td>
                                            </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row mt-4">
                        <div class="col-md-12">
                            <div class="card">
                                <div class="card-header">
                                    <h3 class="card-title">
                                        <i class="fas fa-film mr-1"></i>
                                        Top Movies by Revenue
                                    </h3>
                                </div>
                                <div class="card-body p-0">
                                    <table class="table table-striped">
                                        <thead>
                                            <tr>
                                                <th>Movie</th>
                                                <th>Purchases</th>
                                                <th>Revenue</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach($topMoviesByRevenue as $movie)
                                            <tr>
                                                <td>{{ $movie->title }}</td>
                                                <td>{{ $movie->purchase_count }}</td>
                                                <td>${{ number_format($movie->revenue, 2) }}</td>
                                            </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
</div>
@endsection
